CreateUserRequest=CreateUserResponse: username=username, role=role
DepositMoneyRequest=DepositMoneyResponse:id=id,balance=balance
TransferMoneyRequest=TransferMoneyResponse: senderAccountId=senderAccountId, receiverAccountId=receiverAccountId, amount=amount
UpdateProfileRequest=UpdateProfileResponse: name=customer.name